"""Contracts for generated module output ownership.

Runtime and router files generated by free modules must stay inside the
module-owned namespace so installed workspaces do not mix legacy top-level
layouts with publish-grade module layouts.
"""

from __future__ import annotations

import importlib.util
import inspect
import re
from pathlib import Path
from typing import Any, Iterable

import yaml

MODULES_ROOT = Path(__file__).resolve().parents[2] / "src" / "modules" / "free"


def _module_dirs() -> Iterable[Path]:
    yield from sorted(path.parent for path in MODULES_ROOT.glob("*/*/module.yaml"))


def _load_yaml(path: Path) -> dict[str, Any]:
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict), f"{path} must contain a mapping"
    return loaded


def _module_namespace(module_dir: Path) -> str:
    category, module_name = module_dir.relative_to(MODULES_ROOT).parts[:2]
    return f"src/modules/free/{category}/{module_name}/"


def _is_allowed_src_output(output: str, namespace: str) -> bool:
    if not output.startswith("src/"):
        return True
    if output.startswith(namespace):
        return True
    # Root health shims feed the shared health package/aggregator.
    return output.startswith("src/health/")


def _module_yaml_outputs(module_dir: Path) -> Iterable[tuple[str, str]]:
    config = _load_yaml(module_dir / "module.yaml")
    generation = config.get("generation")
    if not isinstance(generation, dict):
        return

    vendor = generation.get("vendor")
    if isinstance(vendor, dict):
        files = vendor.get("files")
        if isinstance(files, list):
            for index, entry in enumerate(files):
                if isinstance(entry, dict) and isinstance(entry.get("relative"), str):
                    yield (f"generation.vendor.files[{index}].relative", entry["relative"])

    variants = generation.get("variants")
    if isinstance(variants, dict):
        for profile, variant in variants.items():
            if not isinstance(variant, dict):
                continue
            files = variant.get("files")
            if not isinstance(files, list):
                continue
            for index, entry in enumerate(files):
                if isinstance(entry, dict) and isinstance(entry.get("output"), str):
                    yield (f"generation.variants.{profile}.files[{index}].output", entry["output"])


def _nestjs_variant_files(module_dir: Path) -> list[dict[str, Any]]:
    config = _load_yaml(module_dir / "module.yaml")
    generation = config.get("generation")
    if not isinstance(generation, dict):
        return []
    variants = generation.get("variants")
    if not isinstance(variants, dict):
        return []

    variant = variants.get("nestjs") or variants.get("nestjs.standard")
    if not isinstance(variant, dict):
        return []
    files = variant.get("files")
    if not isinstance(files, list):
        return []
    return [entry for entry in files if isinstance(entry, dict)]


def _nestjs_module_output(module_dir: Path) -> str | None:
    for entry in _nestjs_variant_files(module_dir):
        output = entry.get("output")
        if (
            isinstance(output, str)
            and output.startswith("src/modules/")
            and output.endswith(".module.ts")
            and "/health/" not in output
        ):
            return output
    return None


def _nestjs_e2e_templates(module_dir: Path) -> Iterable[Path]:
    for entry in _nestjs_variant_files(module_dir):
        template = entry.get("template")
        if (
            isinstance(template, str)
            and template.startswith("templates/variants/nestjs/tests/")
            and template.endswith(".e2e-spec.ts")
        ):
            yield module_dir / template


def _load_framework_module(framework_file: Path) -> object:
    relative = framework_file.with_suffix("").relative_to(MODULES_ROOT)
    module_name = "rapidkit_namespace_contract_" + "_".join(relative.parts)
    spec = importlib.util.spec_from_file_location(module_name, framework_file)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def _framework_outputs(module_dir: Path) -> Iterable[tuple[str, str]]:
    frameworks_dir = module_dir / "frameworks"
    if not frameworks_dir.exists():
        return
    for framework_file in sorted(frameworks_dir.glob("*.py")):
        if framework_file.name == "__init__.py":
            continue
        module = _load_framework_module(framework_file)
        for _, candidate in inspect.getmembers(module, inspect.isclass):
            if candidate.__module__ != module.__name__:
                continue
            if not candidate.__name__.endswith("Plugin"):
                continue
            plugin = candidate()
            for key, output in plugin.get_output_paths().items():
                if isinstance(output, str):
                    yield (
                        f"{framework_file.relative_to(MODULES_ROOT)}::{candidate.__name__}.{key}",
                        output,
                    )


def test_free_module_src_outputs_are_module_owned() -> None:
    violations: list[str] = []

    for module_dir in _module_dirs():
        namespace = _module_namespace(module_dir)
        for source, output in [*_module_yaml_outputs(module_dir), *_framework_outputs(module_dir)]:
            if not _is_allowed_src_output(output, namespace):
                slug = module_dir.relative_to(MODULES_ROOT).as_posix()
                violations.append(f"{slug}: {source} -> {output} (expected {namespace}*)")

    assert not violations, "Module output namespace drift detected:\n" + "\n".join(violations)


def test_free_module_nestjs_e2e_imports_use_module_alias() -> None:
    violations: list[str] = []

    for module_dir in _module_dirs():
        module_output = _nestjs_module_output(module_dir)
        if not module_output:
            continue
        expected_import = "@modules/" + module_output.removeprefix("src/modules/").removesuffix(
            ".ts"
        )

        for template in _nestjs_e2e_templates(module_dir):
            if not template.exists():
                violations.append(f"{module_dir.relative_to(MODULES_ROOT)}: missing {template}")
                continue
            text = template.read_text(encoding="utf-8")
            imports = re.findall(r"from ['\"]([^'\"]+)['\"]", text)
            module_imports = [value for value in imports if value != "@nestjs/testing"]
            if expected_import not in module_imports:
                violations.append(
                    f"{module_dir.relative_to(MODULES_ROOT)}: {template.name} imports "
                    f"{module_imports or 'nothing'} (expected {expected_import})"
                )
            for value in module_imports:
                if value.startswith("../") and "/src/" in value:
                    violations.append(
                        f"{module_dir.relative_to(MODULES_ROOT)}: {template.name} uses "
                        f"relative src import {value}; use {expected_import}"
                    )

    assert not violations, "NestJS e2e module import drift detected:\n" + "\n".join(violations)
