name: "Bug report"
description: "Report a reproducible bug in rapidkit-core"
title: "[Bug]: "
labels: ["type: bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for opening an issue in RapidKit Core 🚀
  - type: input
    id: version
    attributes:
      label: RapidKit Core version
      placeholder: "e.g. 0.25.1"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "OS, Python version"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1) ... 2) ... 3) ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs / traceback
      render: shell
