#!/usr/bin/env python3
"""
Commit Message Validator

Ensures commit messages follow Conventional Commit best practices:
    type(scope?): description

Also validates body formatting and provides useful suggestions.
"""

import os
import re
import sys
from typing import List, Tuple

# === Configuration ===
MAX_TITLE_LENGTH = 72
EXPECTED_ARG_COUNT = 2
ALLOWED_TYPES: List[str] = [
    "feat",
    "fix",
    "docs",
    "style",
    "refactor",
    "test",
    "chore",
    "perf",
    "ci",
    "build",
    "revert",
    "debug",
    "release",
    "deps",
]
CONVENTIONAL_PATTERN = re.compile(rf"^({'|'.join(ALLOWED_TYPES)})(\([^)]+\))?: .+")

# === Colors ===
RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
RESET = "\033[0m"


def validate_commit_message(message: str) -> Tuple[bool, str]:
    """Validate a commit message string."""
    if not message.strip():
        return False, "Commit message cannot be empty"

    lines = message.strip().split("\n")
    title = lines[0]

    # Allow merge commits (often generated by GitHub), skip strict checks
    lower_title = title.lower()
    if lower_title.startswith("merge "):
        return True, ""

    # Title length check
    if len(title) > MAX_TITLE_LENGTH:
        remaining = MAX_TITLE_LENGTH - len(title)
        return (
            False,
            f"Commit title too long ({len(title)} chars). Exceeds by {-remaining} chars",
        )

    # Conventional commit format check
    if not CONVENTIONAL_PATTERN.match(title):
        return (
            False,
            "Consider using conventional commit format: type(scope): description",
        )

    # Body formatting check (if present)
    if len(lines) > 1:
        if lines[1].strip() != "":
            return (
                False,
                "Second line should be blank before commit body",
            )

    return True, ""


def main() -> None:
    if len(sys.argv) != EXPECTED_ARG_COUNT:
        print("Usage: python scripts/check_commit_message.py '<message>' or <path-to-file>")
        sys.exit(1)

    arg = sys.argv[1]

    if os.path.exists(arg):
        try:
            with open(arg, "r", encoding="utf-8") as f:
                message = f.read().strip()
        except OSError:
            print(f"{RED}❌ Error: Unable to read commit message file: {arg}{RESET}")
            sys.exit(1)
    else:
        message = arg.strip()

    is_valid, error = validate_commit_message(message)

    if is_valid:
        print(f"{GREEN}✅ Commit message is valid{RESET}")
        print(f"📝 {message}")
    else:
        print(f"{RED}❌ Invalid commit message:{RESET}")
        print(f"   {error}\n")
        print(f"{YELLOW}💡 Best practices:{RESET}")
        print(f"   • Keep title under {MAX_TITLE_LENGTH} characters")
        print(
            "   • Use conventional format: "
            "feat/fix/docs/style/refactor/test/chore/perf/ci/build/revert/debug/release/deps"
        )
        print("   • Example: 'feat: Add user authentication system'")

        # Suggest truncation if title too long
        title = message.split("\n")[0]
        if len(title) > MAX_TITLE_LENGTH:
            suggestion = title[:MAX_TITLE_LENGTH]
            print(f'   • Suggested fix: "{suggestion}…"')

        sys.exit(1)


if __name__ == "__main__":
    main()
